name = "WorldDynamics"
uuid = "34572acc-64b2-43ec-bac8-7b2a4baad13f"
authors = ["Emanuele Natale", "Pierluigi Crescenzi", "Paulo Bruno Serafim"]
version = "0.4.4"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
ColorSchemes = "3.0"
ColorTypes = "0.7 - 0.11.5"
DifferentialEquations = "7.1"
IfElse = "0.1.1"
ModelingToolkit = "9.0"
PlotlyJS = "0.13 - 0.18.13"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]